apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: frontend
  newName: pedrohenriquesc/frontend
  newTag: c58b625834eb8b45c0d3d3b45ba4cbc288fc5146
- name: packer-vagrant-virtualbox-main
  newName: pedrohenriquesc/frontend
  newTag: ee189c6e6f14b7ccd7ccccd23e49418b8ebdce9d
